In [1]:
using LinearAlgebra

In [3]:
A = rand(4,4)

4×4 Array{Float64,2}:
 0.113926   0.314578  0.577067  0.348427 
 0.503839   0.355221  0.551054  0.0415172
 0.0797193  0.834561  0.563753  0.725458 
 0.0294199  0.958241  0.586597  0.311062 

In [4]:
ℓ = -A[2, 1] / A[1, 1]

-3.226721866369226

In [16]:
# To make an identity matrix

E_21 = Matrix{Float64}(I, 4, 4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [13]:
E_21[2, 1] = ℓ

-3.226721866369226

In [14]:
E_21

4×4 Array{Float64,2}:
  1.0      0.0  0.0  0.0
 -3.22672  1.0  0.0  0.0
  0.0      0.0  1.0  0.0
  0.0      0.0  0.0  1.0

In [15]:
E_21 * A

4×4 Array{Float64,2}:
 0.302411   0.90948    0.365095   0.290198
 0.0       -2.07988   -0.391539  -0.425093
 0.318987   0.332135   0.499206   0.441944
 0.441313   0.524619   0.182434   0.880558

In [21]:
ℓ_21 = -A[2, 1] / A[1, 1]
E_21 = Matrix{Float64}(I, 4, 4)
E_21[2, 1] = ℓ_21

ℓ_31 = -A[3, 1] / A[1, 1]
E_31 = Matrix{Float64}(I, 4, 4)
E_31[3, 1] = ℓ_31

ℓ_41 = -A[4, 1] / A[1, 1]
E_41 = Matrix{Float64}(I, 4, 4)
E_41[4, 1] = ℓ_41

E_41 * E_31 * E_21 * A

4×4 Array{Float64,2}:
 0.302411   0.90948    0.365095   0.290198
 0.0       -2.07988   -0.391539  -0.425093
 0.0       -0.627197   0.114099   0.135839
 0.0       -0.802599  -0.350355   0.457067

In [39]:
function zero_column(j, A)
    
    U = A
    n = size(A)[1]
    
    for i = j + 1 : n
        ℓ_ij = -A[i, j] / A[j, j]
        E_ij = Matrix{Float64}(I, n, n)
        E_ij[i, j] = ℓ_ij
        
        U = E_ij * U
        
    end
    
    return U
    
end

zero_column (generic function with 1 method)

In [40]:
U = zero_column(1, A)

4×4 Array{Float64,2}:
 0.302411   0.90948    0.365095   0.290198
 0.0       -2.07988   -0.391539  -0.425093
 0.0       -0.627197   0.114099   0.135839
 0.0       -0.802599  -0.350355   0.457067

In [41]:
U = zero_column(2, U)

4×4 Array{Float64,2}:
 0.302411   0.90948   0.365095   0.290198
 0.0       -2.07988  -0.391539  -0.425093
 0.0        0.0       0.232169   0.264028
 0.0        0.0      -0.199265   0.621105

In [42]:
U = zero_column(4, U)

4×4 Array{Float64,2}:
 0.302411   0.90948   0.365095   0.290198
 0.0       -2.07988  -0.391539  -0.425093
 0.0        0.0       0.232169   0.264028
 0.0        0.0      -0.199265   0.621105

In [46]:
function upper_form(A)
    
    n = size(A)[1]
    U = A
    for i = 1 : n - 1
        U = zero_column(i, U)
    end
    return U
end

upper_form (generic function with 1 method)

In [47]:
upper_form(A)

4×4 Array{Float64,2}:
 0.302411   0.90948   0.365095   0.290198
 0.0       -2.07988  -0.391539  -0.425093
 0.0        0.0       0.232169   0.264028
 0.0        0.0       0.0        0.847714

In [48]:
C = rand(10, 10)
upper_form(C)

10×10 Array{Float64,2}:
 0.98643   0.00439921    0.833285   0.0800336  …   0.317149   0.738921  
 0.0       0.766397     -0.499109   0.918021       0.084126   0.291835  
 0.0       0.0           0.955577  -0.761684      -0.107061   0.141727  
 0.0       1.11022e-16   0.0       -0.029368       0.188798  -0.279321  
 0.0       1.70134e-15   0.0        0.0            3.66204   -4.14534   
 0.0      -2.52829e-16   0.0        0.0        …  -0.829576   0.00787532
 0.0      -6.74516e-16   0.0        0.0           -0.646944  -0.583514  
 0.0       1.29309e-16   0.0        0.0            0.163936  -0.132728  
 0.0      -2.98796e-17   0.0        0.0           -0.214203   0.40566   
 0.0      -2.25227e-16   0.0        0.0            0.0        3.14347   

In [1]:
function zero_column(j, A)
    
    U = A
    n = size(A)[1]
    
    for i = j + 1 : n
        ℓ_ij = -A[i, j] / A[j, j]
        E_ij = Matrix{Float64}(I, n, n)
        E_ij[i, j] = ℓ_ij
        
        U = E_ij * U
        
    end
    
    return U
    
end

function upper_form(A)
    
    n = size(A)[1]
    U = A
    for i = 1 : n - 1
        U = zero_column(i, U)
    end
    return U
end


upper_form (generic function with 1 method)

In [68]:
# Practicing the Ux=b function
# first U and b

U = [2.0 3 4 5; 0 3 10 1; 0 0 4 5; 0 0 0 8]
b = [1.0, 2, 3, 4]

4-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0

In [5]:
# just checking to see what this function does

n = size(A)[1]
n

4

In [69]:
# this is what the answer should be 

U \ b

4-element Array{Float64,1}:
 -1.125              
  0.08333333333333333
  0.125              
  0.5                

In [64]:
# defining our own function
# THERE ARE ERRORS, WILL FIX LATER

# know that "zeros(4)" creates an element array of 4 zeros 

function back_solve(U, b)
    
    n = size(U)[1]
    x = zeros(n)
    
    x[n] = b[n] / U[n, n]
    
    for k = n-1 : -1 : 1
        x[k] = (b[k] - sum(U[k, :] * x)) / U[k, k]
    end
    
    return x
end
    
    

back_solve (generic function with 1 method)

In [66]:
x = back_solve(U, b)

MethodError: MethodError: no method matching *(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  *(!Matched::Adjoint{#s623,#s622} where #s622<:Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where #s623, ::Union{DenseArray{S,1}, ReinterpretArray{S,1,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{S,1,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{S,1,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where {T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64}, S} at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\matmul.jl:98
  *(!Matched::Adjoint{#s623,#s622} where #s622<:LinearAlgebra.AbstractTriangular where #s623, ::AbstractArray{T,1} where T) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\triangular.jl:1805
  ...

In [71]:
U = [2.0 3 4 5; 0 3 10 1; 0 0 4 5; 0 0 0 8]
b = [1.0, 2, 3, 4]
x = zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [72]:
x[4] = b[4] / U[4, 4]

0.5

In [73]:
x[3] = (b[3] - (U[3, 4] * x[4])) / U[3, 3]

0.125

In [74]:
x[2] = (b[2] - (U[2, 3] * x[3] + U[2, 4] * x[4])) / U[2,2]

0.08333333333333333

In [76]:
x[1] = (b[1] - (U[1, 2] * x[2] + U[1, 3] * x[3] + U[1, 4] * x[4])) / U[1,1]

-1.125

In [78]:
# Confirming our answers match

U \ b

4-element Array{Float64,1}:
 -1.125              
  0.08333333333333333
  0.125              
  0.5                

In [81]:
# Using list comprehension to find dot product

sum([U[1, i] * [i] for i = 2:4])

1-element Array{Float64,1}:
 38.0

In [84]:
# fixing the error from earlier

function back_solve(U, b)
    
    n = size(U)[1]
    x = zeros(n)
    
    x[n] = b[n] / U[n, n]
    
    # if there's a bounds error it's probably because the next line is wrong, insure these are correct
    for k = n-1 : -1 : 1
        x[k] = (b[k] - sum([U[k, i] * x[i] for i = k+1 : n])) / U[k, k]
    end
    
    return x
end

back_solve (generic function with 1 method)

In [68]:
back_solve(U, b)

4-element Array{Float64,1}:
  2.7642348754448403 
 -1.9715302491103204 
  0.650355871886121  
  0.05693950177935943

In [96]:
# testing the forward solve solution for homework
L = [1.0 0 0; 2 3 0; 4 5 1]
b = [2, 3, 1]


3-element Array{Int64,1}:
 2
 3
 1

In [77]:
L

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 2.0  3.0  0.0
 4.0  5.0  1.0

In [78]:
back_solve(L, b)

3-element Array{Float64,1}:
 2.0
 1.0
 1.0

In [97]:
c = L \ b

3-element Array{Float64,1}:
  2.0               
 -0.3333333333333333
 -5.333333333333333 

In [9]:
b \ c

-0.16666666666666666

In [10]:
c \ b

-0.07167235494880546

In [84]:
# Recalling the formulas from above

function zero_column(j, A)
    
    U = A
    n = size(A)[1]
    
    for i = j + 1 : n
        ℓ_ij = -A[i, j] / A[j, j]
        E_ij = Matrix{Float64}(I, n, n)
        E_ij[i, j] = ℓ_ij
        
        U = E_ij * U
        
    end
    
    return U
    
end

function upper_form(A)
    
    n = size(A)[1]
    U = A
    for i = 1 : n - 1
        U = zero_column(i, U)
    end
    return U
end

function back_solve(U, b)
    
    n = size(U)[1]
    x = zeros(n)
    
    x[n] = b[n] / U[n, n]
    
    # if there's a bounds error it's probably because the next line is wrong, insure these are correct
    for k = n-1 : -1 : 1
        x[k] = (b[k] - sum([U[k, i] * x[i] for i = k+1 : n])) / U[k, k]
    end
    
    return x
end

back_solve (generic function with 1 method)

# HOMEWORK

In [6]:
using LinearAlgebra

L = [1.0 0 0; 2 3 0; 4 5 1]
b = [2, 3, 1]

3-element Array{Int64,1}:
 2
 3
 1

In [7]:
# using these to compare my values to
L \ b

3-element Array{Float64,1}:
  2.0               
 -0.3333333333333333
 -5.333333333333333 

In [11]:
function forward_solve(L, b)
    
    n = size(L)[1]
    c = zeros(n)
    
    c[1] = b[1] / L[1, 1]
    
    for k = 2 : n
        c[k] = (b[k] - sum([L[k, i] * c[i] for i = 1 : k - 1])) / L[k, k]
    end
    
    return c
end

forward_solve (generic function with 1 method)

In [12]:
forward_solve(L, b)

3-element Array{Float64,1}:
  2.0               
 -0.3333333333333333
 -5.333333333333334 

# IN CLASS WORK 1/30

In [107]:
function LU(A)
    U = copy(A)
    m = size(A)[1]
    L = Matrix{Float64}(I, m, m)
    
    for k = 1 : m - 1
        for j = k + 1 : m
            L[j,k] = U[j,k] / U[k,k]
            U[j,k:m] = U[j,k:m] - L[j,k] * U[k, k:m]
        end
    end
    return L, U
end


LU (generic function with 1 method)

In [108]:
A = [2 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8]

4×4 Array{Int64,2}:
 2  1  1  0
 4  3  3  1
 8  7  9  5
 6  7  9  8

In [110]:
L, U = LU(A)

([1.0 0.0 0.0 0.0; 2.0 1.0 0.0 0.0; 4.0 3.0 1.0 0.0; 3.0 4.0 1.0 1.0], [2 1 1 0; 0 1 1 1; 0 0 2 2; 0 0 0 2])

In [111]:
print(A)
print(L)
print(U)

[2 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8][1.0 0.0 0.0 0.0; 2.0 1.0 0.0 0.0; 4.0 3.0 1.0 0.0; 3.0 4.0 1.0 1.0][2 1 1 0; 0 1 1 1; 0 0 2 2; 0 0 0 2]

In [112]:
function forward_solve(L, b)
    
    n = size(L)[1]
    c = zeros(n)
    
    c[1] = b[1] / L[1, 1]
    
    for k = 2 : n
        c[k] = (b[k] - sum([L[k, i] * c[i] for i = 1 : k - 1])) / L[k, k]
    end
    
    return c
end

forward_solve (generic function with 1 method)

In [113]:
function back_solve(U, b)
    
    n = size(U)[1]
    x = zeros(n)
    
    x[n] = b[n] / U[n, n]
    
    # if there's a bounds error it's probably because the next line is wrong, insure these are correct
    for k = n-1 : -1 : 1
        x[k] = (b[k] - sum([U[k, i] * x[i] for i = k+1 : n])) / U[k, k]
    end
    
    return x
end

back_solve (generic function with 1 method)

In [114]:
function solve_system(A, b)
    L, U = LU(A)
    c = forward_solve(L, b)
    x = back_solve(U, c)
    return x
end

solve_system (generic function with 1 method)

In [115]:
A = rand(10000, 10000)
b = rand(10000)

10000-element Array{Float64,1}:
 0.5006440328057415  
 0.7485704963900002  
 0.6369347766626821  
 0.88937213963839    
 0.1467825841790611  
 0.41843881390910753 
 0.03511807084003293 
 0.403037819300208   
 0.6608439573825553  
 0.012455795353099708
 0.34778222014361493 
 0.6560048104802327  
 0.10536773899572327 
 ⋮                   
 0.6548402291808721  
 0.5853588879450577  
 0.9670887536718993  
 0.5700095090543227  
 0.1808824453820168  
 0.6416261359734705  
 0.17886635533260797 
 0.9967392863536155  
 0.6430257901639398  
 0.25136732429647135 
 0.6678532545986204  
 0.6537127041197208  

In [116]:
A\ b

10000-element Array{Float64,1}:
  1.0963997805148613  
 -1.745316462407167   
  1.866725718150959   
 -1.7373968245848876  
  0.6893176681099858  
  1.9880775760096085  
 -0.05869112023509631 
  1.0999158147507975  
  1.3022539933905823  
 -0.18142463001540302 
 -0.4345114821818516  
 -2.0071005409607907  
  0.21148931125257447 
  ⋮                   
  0.15981688443750267 
 -0.2331739134401046  
  0.807449537284557   
 -1.6819416863596879  
 -1.8531287987425293  
  1.0433285014871871  
  0.6655839717225329  
  0.024434255890953813
  0.8280679374833548  
 -0.8291348322232751  
  1.832879868187486   
 -1.0963099610475284  